spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/web7_2024
    username: postgres
    password: 123456789
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: eshop27test@gmail.com
    password: mborsyryruuaogqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 60m
    redis:
      flush-mode: on_save
      namespace: spring:session

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1h
    socket-timeout: 1h
    socket-keep-alive: true

paypal:
  client-id: AW_5MMhcrPFesiPe4ZepeZnUsswE8lUDOR-JVL8n5JVM0MQSfpMSGHsey9u-FGhSFh47Ds6FkTHOzCTm
  client-secret: EBRREP7zirrL6RirXPZ_vdvtqxftx1NSUlw6XvVCQkWdal1--qRSsrnB1ewNR2blhU7gGEgKsRawTGfj
  mode: sandbox

server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error

logging:
  level:
    com:
      springboot:
        ecommerce: DEBUG
